# Generated by Django 5.2.7 on 2025-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='hours_worked',
            field=models.FloatField(default=0),
        ),
    ]
